### ISSUE TITLE
Can't get the master branch to run

### ISSUE THREAD

**Issue by 4996wsu** [omerkhan3/CSC4996-CarpoolApp#1]
There are errors in master. Fix these ASAP. Master should be runnable all the time. If there are manual steps, include them in the README.md

<img width="275" alt="screen shot 2018-01-30 at 5 52 33 pm" src="https://user-images.githubusercontent.com/25090751/35595959-62b2d832-05e6-11e8-8cda-5091c6fb9ab2.png">

Once this is fixed, let me know. I will verify and close this issue.

**Comment by omerkhan3** [comment]
This is an issue with the configuration of the Pods associated with the project when first downloaded.  I have included steps on how to configure the project in the README.md file.  I cloned the project to a new machine and was able to replicate and resolve your errors following these steps.  Please let me know if this resolves the issue.
