### ISSUE TITLE
Update invalid user alert

### ISSUE THREAD

**Issue by ba6037** [omerkhan3/CSC4996-CarpoolApp#13]
Change to "Error! Email address entered has not been registered. Please enter a valid email address or register a new account."

![image](https://user-images.githubusercontent.com/35587411/38166972-440a362a-34fb-11e8-8426-f645e25db0bc.png)

**Comment by mpgrande7** [comment]
this is a default response from firebase auth, no way to change unless we make a general statement saying email and password is wrong and they should retry, no way to distinguish between an unregistered email address from an incorrect password

**Comment by omerkhan3** [comment]
I'm okay with leaving as-is in that case.

**Comment by omerkhan3** [comment]
You can do a check to see if the error message is equal to this, and use our own custom message.
